In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as sns
import seaborn as snS

import nltk
from sentence_transformers import SentenceTransformer

import re
from pathlib import Path
from zipfile import ZipFile

In [3]:
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to C:\Users\MY
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [4]:
DATAFILES_PATH = "../Data"

In [5]:
list(Path(DATAFILES_PATH).rglob("*"))

[WindowsPath('../Data/Cleaned_articles'),
 WindowsPath('../Data/Guidlines'),
 WindowsPath('../Data/Hospital_docs'),
 WindowsPath('../Data/Reports'),
 WindowsPath('../Data/Research_papers'),
 WindowsPath('../Data/Tables'),
 WindowsPath('../Data/Cleaned_articles/archive.zip'),
 WindowsPath('../Data/Cleaned_articles/articles'),
 WindowsPath('../Data/Cleaned_articles/articles/1.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/10.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/100.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1000.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1001.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1002.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1003.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1004.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1005.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1006.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1007.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1008.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1009.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/101.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1010.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1011.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1012.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1013.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1014.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1015.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1016.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1017.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1018.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1019.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/102.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1020.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1021.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1022.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1023.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1024.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1025.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1026.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1027.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1028.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1029.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/103.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1030.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1031.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1032.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1033.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1034.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1035.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1036.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1037.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1038.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1039.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/104.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1040.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1041.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1042.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1043.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1044.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1045.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1046.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1047.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1048.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1049.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/105.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1050.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1051.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1052.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1053.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1054.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1055.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1056.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1057.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1058.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1059.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/106.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1060.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1061.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1062.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1063.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1064.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1065.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1066.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1067.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1068.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1069.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/107.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1070.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1071.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1072.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1073.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1074.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1075.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1076.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1077.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1078.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1079.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/108.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1080.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1081.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1082.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1083.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1084.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1085.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1086.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1087.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1088.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1089.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/109.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1090.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1091.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1092.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1093.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1094.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1095.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1096.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1097.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1098.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1099.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/11.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/110.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1100.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1101.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1102.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1103.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1104.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1105.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1106.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1107.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1108.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1109.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/111.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1110.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1111.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1112.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1113.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1114.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1115.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1116.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1117.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1118.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1119.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/112.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1120.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1121.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1122.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1123.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1124.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1125.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1126.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1127.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1128.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1129.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/113.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1130.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1131.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1132.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1133.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1134.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1135.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1136.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1137.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1138.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1139.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/114.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1140.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1141.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1142.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1143.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1144.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1145.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1146.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1147.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1148.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1149.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/115.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1150.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1151.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1152.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1153.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1154.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1155.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1156.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1157.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1158.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1159.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/116.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1160.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1161.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1162.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1163.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1164.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1165.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1166.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1167.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1168.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1169.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/117.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1170.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1171.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1172.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1173.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1174.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1175.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1176.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1177.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1178.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1179.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/118.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1180.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1181.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1182.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1183.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1184.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1185.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1186.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1187.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1188.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1189.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/119.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1190.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1191.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1192.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1193.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1194.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1195.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1196.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1197.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1198.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1199.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/12.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/120.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1200.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1201.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1202.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1203.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1204.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1205.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1206.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1207.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1208.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1209.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/121.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1210.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1211.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1212.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1213.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1214.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1215.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1216.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1217.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1218.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1219.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/122.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1220.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1221.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1222.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1223.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1224.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1225.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1226.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1227.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1228.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1229.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/123.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1230.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1231.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1232.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1233.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1234.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1235.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1236.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1237.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1238.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1239.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/124.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1240.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1241.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1242.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1243.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1244.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1245.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1246.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1247.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1248.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1249.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/125.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1250.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1251.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1252.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1253.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1254.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1255.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1256.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1257.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1258.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1259.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/126.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1260.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1261.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1262.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1263.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1264.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1265.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1266.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1267.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1268.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1269.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/127.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1270.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1271.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1272.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1273.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1274.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1275.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1276.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1277.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1278.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1279.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/128.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1280.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1281.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1282.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1283.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1284.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1285.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1286.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1287.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1288.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1289.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/129.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1290.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1291.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1292.txt'),
 WindowsPath('../Data/Cleaned_articles/articles/1293.txt'),

In [6]:
def get_file_list(data_path=DATAFILES_PATH):
    data_path = Path(data_path)
    dirs = []
    files = []

    for item in data_path.rglob("*"):
        if item.is_dir():
            dirs.append(item)
        else:
            files.append(item)

    all_files = [str(i) for i in files if not (Path(i).is_dir() or str(i).endswith(".zip"))]
    pdf_files = [str(i) for i in all_files if str(i).endswith(".pdf")]
    txt_files = [str(i) for i in all_files if str(i).endswith(".txt")]
    csv_files = [str(i) for i in all_files if str(i).endswith(".csv")]
    
    return all_files, pdf_files, txt_files, csv_files

In [7]:
all_files, pdf_files, txt_files, csv_files = get_file_list()

In [8]:
csv_files

['..\\Data\\Tables\\Diseases_Symptoms.csv',
 '..\\Data\\Tables\\medquad.csv',
 '..\\Data\\Tables\\Symptom2Disease.csv']

In [ ]:
def clean_txt_file(txt_file):
    doc_name = Path(txt_file).stem
    doc_type = Path(txt_file).suffix

    with open(txt_file, 'r', encoding='utf-8', errors='ignore') as file:
        text = file.read()
    
    # Remove special characters and digits
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Tokenize and remove stop words
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    
    cleaned_text = ' '.join(tokens)
    return cleaned_text

In [39]:
def clean_csv_file(csv_file):
    doc_name = Path(csv_file).stem
    doc_type = Path(csv_file).suffix
    
    df = pd.read_csv(csv_file)

    df.dropna(inplace=True)  # drop rows with any NaN values
    df = df.select_dtypes(include=[object])  # select only string columns

    def clean_text(row):
        new_list = []
        for col in row.index:  # iterate through columns
            new_list.append(f"{col.capitalize()}: {row[col]}")  
        return ". ".join(new_list)
    

    return doc_type, doc_name, df.apply(clean_text, axis=1).to_list()

In [38]:
clean_csv_file(csv_files[1])[0]

'.csv'

In [ ]:
pd.read_csv(csv_files[0]).head()

,Code,Name,Symptoms,Treatments
0,1,Panic disorder,"Palpitations, Sweating, Trembling, Shortness o...","Antidepressant medications, Cognitive Behavior..."
1,2,Vocal cord polyp,"Hoarseness, Vocal Changes, Vocal Fatigue","Voice Rest, Speech Therapy, Surgical Removal"
2,3,Turner syndrome,"Short stature, Gonadal dysgenesis, Webbed neck...","Growth hormone therapy, Estrogen replacement t..."
3,4,Cryptorchidism,"Absence or undescended testicle(s), empty scro...",Observation and monitoring (in cases of mild o...
4,5,Ethylene glycol poisoning-1,"Nausea, vomiting, abdominal pain, General mala...","Supportive Measures, Gastric Decontamination, ..."

In [ ]:
df_trial = pd.read_csv(csv_files[2])
df_trial.head()

df_trial = df_trial.select_dtypes(include=[object]).head()

def clean_text(row):
    new_list = []
    for col in row.index:  # iterate through columns
        new_list.append(f"{col.capitalize()}: {row[col]}")  
    return ". ".join(new_list)

df_trial.apply(clean_text, axis=1).to_list()

['Label: Psoriasis. Text: I have been experiencing a skin rash on my arms, legs, and torso for the past few weeks. It is red, itchy, and covered in dry, scaly patches.',
 'Label: Psoriasis. Text: My skin has been peeling, especially on my knees, elbows, and scalp. This peeling is often accompanied by a burning or stinging sensation.',
 'Label: Psoriasis. Text: I have been experiencing joint pain in my fingers, wrists, and knees. The pain is often achy and throbbing, and it gets worse when I move my joints.',
 'Label: Psoriasis. Text: There is a silver like dusting on my skin, especially on my lower back and scalp. This dusting is made up of small scales that flake off easily when I scratch them.',
 'Label: Psoriasis. Text: My nails have small dents or pits in them, and they often feel inflammatory and tender to the touch. Even there are minor rashes on my arms.']

In [16]:
pd.read_csv(csv_files[1]).head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [ ]:
pd.read_csv(csv_files[2]).head()

   Unnamed: 0      label                                               text
0           0  Psoriasis  I have been experiencing a skin rash on my arm...
1           1  Psoriasis  My skin has been peeling, especially on my kne...
2           2  Psoriasis  I have been experiencing joint pain in my fing...
3           3  Psoriasis  There is a silver like dusting on my skin, esp...
4           4  Psoriasis  My nails have small dents or pits in them, and...

In [24]:
text_data = []
for i in txt_files:
    with open(i, 'r', encoding='utf-8') as file:
        text_data.append(file.read())

In [ ]:
model = SentenceTransformer('all-mpnet-base-v2')

model.encode(text_data)